// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBCandidate
    {
        public DBCandidate()
        {
            CandidateLinks = new HashSet<DBCandidateLink>();
            Interviews = new HashSet<DBInterview>();
            OfferLetters = new HashSet<DBOfferLetter>();
            IdJobOpenings = new HashSet<DBJobOpening>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string CoverLetter { get; set; }
        public string UploadResume { get; set; }
        public bool? IsActive { get; set; }
        public int IdJobOpening { get; set; }

        public virtual ICollection<DBCandidateLink> CandidateLinks { get; set; }
        public virtual ICollection<DBInterview> Interviews { get; set; }
        public virtual ICollection<DBOfferLetter> OfferLetters { get; set; }

        public virtual ICollection<DBJobOpening> IdJobOpenings { get; set; }
    }
}