// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBCandidateLink
    {
        public string Link { get; set; }
        public int IdCandidate { get; set; }

        public virtual DBCandidate IdCandidateNavigation { get; set; }
    }
}