// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBHr
    {
        public int IdInterview { get; set; }
        public int? SalaryExpected { get; set; }

        public virtual DBInterview IdInterviewNavigation { get; set; }
    }
}