// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBInterview
    {
        public int Id { get; set; }
        public string InterviewName { get; set; }
        public DateTime InterviewDate { get; set; }
        public string FeedBack { get; set; }
        public bool IsApproved { get; set; }
        public string Reason { get; set; }
        public int IdCandidate { get; set; }
        public int IdJobOpening { get; set; }
        public int IdUser { get; set; }

        public virtual DBCandidate IdCandidateNavigation { get; set; }
        public virtual DBJobOpening IdJobOpeningNavigation { get; set; }
        public virtual DBUserR IdUserNavigation { get; set; }
        public virtual DBCultural Cultural { get; set; }
        public virtual DBHr Hr { get; set; }
        public virtual DBManager Manager { get; set; }
        public virtual DBTechnical Technical { get; set; }
        public virtual DBVp Vp { get; set; }
    }
}