// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBInterviewType
    {
        public DBInterviewType()
        {
            IdUserRs = new HashSet<DBUserR>();
        }

        public int Id { get; set; }
        public string IType { get; set; }

        public virtual ICollection<DBUserR> IdUserRs { get; set; }
    }
}