// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBJobOpening
    {
        public DBJobOpening()
        {
            Interviews = new HashSet<DBInterview>();
            OfferLetters = new HashSet<DBOfferLetter>();
            IdCandidates = new HashSet<DBCandidate>();
        }

        public int Id { get; set; }
        public string Position { get; set; }
        public int? OpenPositions { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string JobSummary { get; set; }
        public string Link { get; set; }

        public virtual ICollection<DBInterview> Interviews { get; set; }
        public virtual ICollection<DBOfferLetter> OfferLetters { get; set; }

        public virtual ICollection<DBCandidate> IdCandidates { get; set; }
    }
}