// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TraineeProgram.Persistence.DBEntities
{
    public partial class DBUserR
    {
        public DBUserR()
        {
            Interviews = new HashSet<DBInterview>();
            OfferLetters = new HashSet<DBOfferLetter>();
            IdTypes = new HashSet<DBInterviewType>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public int UserRole { get; set; }
        public string Password { get; set; }
        public byte[] Photo { get; set; }

        public virtual ICollection<DBInterview> Interviews { get; set; }
        public virtual ICollection<DBOfferLetter> OfferLetters { get; set; }

        public virtual ICollection<DBInterviewType> IdTypes { get; set; }
    }
}